name: Continuous Integration
on:
  # Run on manual trigger
  workflow_dispatch:

  # Run on pull requests
  pull_request:
    paths-ignore:
      - '*.md'

  # Run when pushing to main or dev branches
  push:
    branches:
      - main
      - dev*

  # Run scheduled CI flow daily
  schedule:
    - cron: '0 8 * * 0'

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: TensorFlow 1.15.5 (Keras 2.2.5 Python 3.7)
            framework: tensorflow
            python: 3.7
            tensorflow: 1.15.5
            tf_version: v1
            keras: 2.2.5
          - name: TensorFlow 2.3.2 (Keras 2.4.3 Python 3.7)
            framework: tensorflow
            python: 3.7
            tensorflow: 2.3.2
            tf_version: v2
            keras: 2.4.3
          - name: TensorFlow 2.4.1v1 (Keras 2.4.3 Python 3.8)
            framework: tensorflow2v1
            python: 3.8
            tensorflow: 2.4.1
            tf_version: v2
            keras: 2.4.3
          - name: TensorFlow 2.4.1 (Keras 2.4.3 Python 3.8)
            framework: tensorflow
            python: 3.8
            tensorflow: 2.4.1
            tf_version: v2
            keras: 2.4.3
          - name: Keras 2.3.1 (TensorFlow 2.2.1 Python 3.7)
            framework: keras
            python: 3.7
            tensorflow: 2.2.1
            keras: 2.3.1
          - name: TensorFlow-Keras 2.3.2 (Keras 2.4.3 Python 3.7)
            framework: kerastf
            python: 3.7
            tensorflow: 2.3.2
            keras: 2.4.3
          - name: PyTorch (Python 3.7)
            framework: pytorch
            python: 3.7
            torch: 1.7.1+cpu
            torchvision: 0.8.2+cpu
            torchaudio: 0.7.2
          - name: scikit-learn 0.22.2 (Python 3.7)
            framework: scikitlearn
            scikit-learn: 0.22.2
            python: 3.7
          - name: scikit-learn 0.23.2 (Python 3.8)
            framework: scikitlearn
            scikit-learn: 0.23.2
            python: 3.8
          - name: TensorFlow+Lingvo 2.1.0v1 (Keras 2.3.1 Python 3.6)
            framework: tensorflow2v1
            python: 3.6
            tensorflow: 2.1.0
            tf_version: v2
            keras: 2.3.1
            lingvo: 0.6.4
#          - name: mxnet (Python 3.7)
#            framework: mxnet
#            python: 3.7
#          - name: legacy (TensorFlow 2.3.2 Keras 2.4.3  PyTorch 1.7.1 scikit-learn 0.22.2 Python 3.7)
#            framework: legacy
#            python: 3.7
#            tensorflow: 2.3.2
#            keras: 2.4.3
#            scikit-learn: 0.22.2
#            torch: 1.7.1+cpu
#            torchvision: 0.8.2+cpu
#            torchaudio: 0.7.2
#          - name: legacy (TensorFlow 2.4.1 Keras 2.4.3 PyTorch 1.7.1 scikit-learn 0.23.2 Python 3.7)
#            framework: legacy
#            python: 3.7
#            tensorflow: 2.4.1
#            keras: 2.4.3
#            torch: 1.7.1+cpu
#            torchvision: 0.8.2+cpu
#            torchaudio: 0.7.2
#            scikit-learn: 0.23.2

    name: Run ${{ matrix.name }} Tests
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y -q install ffmpeg libavcodec-extra
          python -m pip install --upgrade pip setuptools wheel
          pip install tensorflow==2.4.1
          pip install keras==2.4.3
          pip3 install -q -r requirements.txt
          pip list
      - name: Pre-install legacy
        if: ${{ matrix.framework == 'legacy' }}
        run: |
          pip install tensorflow==${{ matrix.tensorflow }}
          pip install keras==${{ matrix.keras }}
          pip install scikit-learn==${{ matrix.scikit-learn }}
          pip install torch==${{ matrix.torch }} -f https://download.pytorch.org/whl/torch_stable.html
          pip install torchvision==${{ matrix.torchvision }} -f https://download.pytorch.org/whl/torch_stable.html
          pip install torchaudio==${{ matrix.torchaudio }} -f https://download.pytorch.org/whl/torch_stable.html
          pip list
      - name: Pre-install tensorflow
        if: ${{ matrix.framework == 'tensorflow' || matrix.framework == 'keras' || matrix.framework == 'kerastf' || matrix.framework == 'tensorflow2v1' }}
        run: |
          pip install tensorflow==${{ matrix.tensorflow }}
          pip install keras==${{ matrix.keras }}
          pip list
      - name: Pre-install scikit-learn
        if: ${{ matrix.framework == 'scikitlearn' }}
        run: |
          pip install scikit-learn==${{ matrix.scikit-learn }}
          pip list
      - name: Pre-install torch
        if: ${{ matrix.framework == 'pytorch' }}
        run: |
          pip install torch==${{ matrix.torch }} -f https://download.pytorch.org/whl/torch_stable.html
          pip install torchvision==${{ matrix.torchvision }} -f https://download.pytorch.org/whl/torch_stable.html
          pip install torchaudio==${{ matrix.torchaudio }} -f https://download.pytorch.org/whl/torch_stable.html
      - name: Pre-install Lingvo ASR
        if: ${{ matrix.tensorflow == '2.1.0' }}
        run: |
          pip install tensorflow==${{ matrix.tensorflow }}
          pip install lingvo==${{ matrix.lingvo }}
          pip install tensorflow-addons==0.9.1
          pip install model-pruning-google-research==0.0.3
          pip list
      - name: Run ${{ matrix.name }} Tests
        run: ./run_tests.sh ${{ matrix.framework }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
  style:
    name: Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Pre-install
        run: |
          sudo apt-get update
          sudo apt-get -y -q install ffmpeg libavcodec-extra
          pip install tensorflow==2.2.2
          pip install keras==2.3.1
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -q pylint pycodestyle
          pip install -q -r requirements.txt
          pip list
      - name: pycodestyle
        run: (pycodestyle --ignore=C0330,C0415,E203,E231,W503 --max-line-length=120 art || exit 0)
      - name: pylint
        run: (pylint --disable=C0330,C0415,E203,E1136 -rn art || exit 0)
      - name: Check Types (mypy)
        run: (mypy art || exit 0)
      - name: pytest
        run: py.test --pep8 -m pep8
